/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QueryDemo } from "./QueryDemo";
export * as factories from "./factories";
export { QueryDemo__factory } from "./factories/QueryDemo__factory";
